language: csharp
sudo: false
mono:
  - 4.6.2 # in most common distros
  - 4.2.1 # in Ubuntu LTS
  - 5.0.1 # latest stable
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      mono: 5.0.1
  allow_failures:
    - os: osx
    - mono: 5.0.1
  fast_finish: true
script:
  - ./build.sh --target "Travis"