language: csharp
sudo: false
dotnet: 2.0.3
matrix:
  include:
    - os: linux
      mono: 4.6.2
    - os: linux
      mono: latest
    - os: osx
      mono: latest
script:
  - ./build.sh --target "Travis" --configuration "Release"
