language: csharp
sudo: false

dotnet: 3.0.100
mono: 6.4.0

matrix:
  include:
  - dist: xenial
    env: DOTNET_INSTALL_DIR=/usr/share/dotnet

  - os: osx
    env: DOTNET_INSTALL_DIR=/usr/local/share/dotnet

install: |
  curl -O -sSL https://dot.net/v1/dotnet-install.sh
  chmod +x dotnet-install.sh

  for channel in 2.1 2.2
  do
    sudo -s ./dotnet-install.sh --install-dir $DOTNET_INSTALL_DIR --runtime dotnet --channel $channel
  done

- dotnet tool install --tool-path tools Cake.Tool

script:
- ./tools/dotnet-cake --target=Travis --configuration=Release
